[env:nucleo_f091rc]
platform = ststm32
board = nucleo_f091rc
framework = cmsis

; --- Build Configuration ---
board_build.f_cpu = 48000000L
build_flags = 
    -Wl,-u_printf_float

; --- Serial Monitor ---
monitor_speed = 115200
monitor_eol = LF

; --- Custom Bare Metal Upload using STM32Cube CLI ---
; --- Custom Bare Metal Upload using STM32Cube CLI ---
upload_protocol = custom
upload_command = /usr/local/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin/STM32_Programmer_CLI -c port=SWD freq=240 mode=HOTPLUG -w .pio/build/nucleo_f091rc/firmware.elf -v